########## Server properties ############
# Security System name
# Depends on server setup
# Keep it empty on local environment
security.system.name=

# Application name
application.name=designer

# Project name
project.name=portal

# Server host
server.host=localhost

# Server port
server.port=8081

########## Load profile ############
# Virtual users to ramp to, and ramp-up period in seconds.
load.users=1
load.rampup=1

##### CSV file for user
one_user.csv=resources/one_user.csv
